[package]
name = "dec-06"
version = "0.1.0"
authors = ["Van Man Nguyen <vanman.nguyen@outlook.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
